fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: rust-fmt
        name: rust-fmt
        description: Check if all files follow the rust-fmt style
        # https://github.com/pre-commit-ci/issues/issues/121
        entry: cargo fmt -- --check --color always
        language: rust
        pass_filenames: false
