from typing import Tuple

def decode(hash: str) -> Tuple[float, float]: ...
def decode_exact(hash: str) -> Tuple[float, float, float, float]: ...
def encode(lat: float, lon: float, len: int = 12) -> str: ...
def bbox(hash: str) -> Tuple[float, float, float, float]: ...
def neighbors(hash: str) -> dict[str, str]: ...
def neighbor(hash: str, direction: str) -> str: ...


class DecodeError(ValueError): ...
class EncodeError(ValueError): ...
class ParamError(SyntaxError): ...
